### ISSUE TITLE
Postman returns invalidCredentials when posting to Login method

### ISSUE THREAD

**Issue by fvvliet** [truemetal/vapor-2-heroku-auth-template#1]
When using Postman to test this REST API, I keep getting 'invalidCredentials' error when calling the 'Login' method (with Basic Auth header key). For some reason the verify() in Hash extension of BCrypt 1.1.0 dependency fails but I don't know why.

Anyone any idea how to fix this ?

thanks in advance
Frank

**Comment by truemetal** [comment]
Hey @fvvliet , does that happen out of the box with built in user tokens e.g. `u1 token`?

**Comment by fvvliet** [comment]
Yes it does. Steps I took to run the template locally (on macOS):
- create project with this template 
- vapor xcode
- run ./crypto.sh
- launch project from XCode
- call 'Login' with username 'u1' and password in Postman. Postman uses Basic Auth.
- response "Authentication.AuthenticationError.invalidCredentials"

The other calls with a Bearer token do work fine in Postman but the Login doesn't.

**Comment by truemetal** [comment]
@fvvliet well, I've just pulled and tested and it works for me (screenshot attached).

Please make sure you enter the correct password.
I'm closing the issue, if you did check the password and it still does not work for you - please feel free to reopen.

![screen shot 2018-02-27 at 12 15 25](https://user-images.githubusercontent.com/2472186/36723104-fca4b258-1bb7-11e8-8ff3-418da82c2dce.png)

**Comment by fvvliet** [comment]
Yes it's the password. Thanks for your help !
